'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
type Role='cash'|'activity'|null; type Section='operating'|'investing'|'financing'|null;
interface A{id:string;name:string;coa_code?:string|null;account_type:string;normal_balance:string;cash_flow_role?:Role;cash_flow_section?:Section}
export default function CashFlowClassificationPanel({clientId,canManage}:{clientId:string;canManage:boolean}){const[a,setA]=useState<A[]>([]),[loading,setLoading]=useState(true),[acting,setActing]=useState<string|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/cash-flow-classification?clientId=${encodeURIComponent(clientId)}`,{cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to load cash-flow classifications.');setA(j.categories||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load cash-flow classifications.')}finally{setLoading(false)}},[clientId]);useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(cancelled)return;setMessage('');void load()});return()=>{cancelled=true}},[load]);const classified=useMemo(()=>a.filter(x=>x.cash_flow_role).length,[a]);
async function change(x:A,v:string){if(!canManage||acting)return;let role:Role=null,section:Section=null;if(v==='cash')role='cash';else if(v.startsWith('activity:')){role='activity';section=v.slice(9) as Section}try{setActing(x.id);setError('');setMessage('');const r=await fetch('/api/cash-flow-classification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,categoryId:x.id,role,section})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to save classification.');setMessage('Cash-flow classification saved and audit history updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save classification.')}finally{setActing(null)}}
const val=(x:A)=>x.cash_flow_role==='cash'?'cash':x.cash_flow_role==='activity'&&x.cash_flow_section?`activity:${x.cash_flow_section}`:'';
return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Cash Flow Classification</h2><p className="mt-1 text-sm text-slate-400">Identify cash accounts and classify the non-cash accounts used to explain cash movements.</p></div><div className="rounded-full border border-slate-700 px-3 py-1 text-xs font-semibold text-slate-300">{classified} of {a.length} classified</div></div><p className="mt-3 text-xs text-slate-500">LedgerAI does not guess these classifications. Cash / Cash Equivalent is available only for Asset accounts. Activity accounts must be Operating, Investing, or Financing.</p>{error&&<div className="mt-4 rounded-lg border border-red-900/60 bg-red-950/30 px-4 py-3 text-sm text-red-300">{error}</div>}{message&&<div className="mt-4 rounded-lg border border-emerald-900/60 bg-emerald-950/30 px-4 py-3 text-sm text-emerald-300">{message}</div>}{loading?<p className="mt-5 text-sm text-slate-500">Loading cash-flow classifications…</p>:a.length===0?<p className="mt-5 text-sm text-slate-500">No eligible posting accounts are available.</p>:<div className="mt-5 space-y-3">{a.map(x=><div key={x.id} className="grid gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-4 md:grid-cols-[minmax(0,1fr)_280px] md:items-center"><div><p className="font-medium text-slate-100">{x.coa_code?`${x.coa_code} · `:''}{x.name} · {x.account_type}</p><p className="mt-1 text-xs text-slate-500">Normal balance: {x.normal_balance}</p></div><select value={val(x)} disabled={!canManage||!!acting} onChange={e=>void change(x,e.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200 disabled:opacity-50"><option value="">Unclassified</option>{x.account_type==='asset'&&<option value="cash">Cash / Cash Equivalent</option>}<option value="activity:operating">Activity · Operating</option><option value="activity:investing">Activity · Investing</option><option value="activity:financing">Activity · Financing</option></select></div>)}</div>}{!canManage&&<p className="mt-4 text-xs text-amber-300">Owner, admin, or bookkeeper access is required to change cash-flow classifications.</p>}</section>}
